import { ThemeChangeProvider } from "@/providers/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeChangeProvider>
      <html lang="en">
        <Script
          src="https://kit.fontawesome.com/d37f4b642f.js"
          crossOrigin="anonymous"
        ></Script>
        <body className={nunito.className}>{children}</body>
      </html>
    </ThemeChangeProvider>
  );
}
